# One-Hot Encoding Clean Games Dataset

The Games dataset has been cleaned in 'data_analysis_and_cleaning_games_dataset.ipynb'. 

Two of the columns in the clean Games contain categorical data (Genre and Team), one of the objectives is to test whether one-hot encoding these columns and including them in the Decision Trees and Random Forests produce better results than excluding them altogether.

In [2]:
import pandas as pd

In [3]:
# create a pandas DataFrame called "games" containing the clean data

games = pd.read_csv('C:/Users/Mark/Documents/repos/group-coursework-ha/data/games_clean.csv')

In [5]:
# display the top five rows of the DataFrame to confirm the clean data has been imported properly and is ready to be one-hot encoded

games.head()

,Title,Team,Rating,Number of Reviews,Genres,Plays,Playing,Active Users
0,Elden Ring,Bandai Namco Entertainment,4.5,3900,Adventure,17000,3800,0.22
1,Hades,Supergiant Games,4.3,2900,Adventure,21000,3200,0.15
2,The Legend of Zelda: Breath of the Wild,Nintendo,4.4,4300,Adventure,30000,2500,0.08
3,Undertale,tobyfox,4.2,3500,Adventure,28000,679,0.02
4,Hollow Knight,Team Cherry,4.4,3000,Adventure,21000,2400,0.11

# One-Hot Encoding

In [156]:
# One-Hot Encode Team and Genres columns

# Team and Genres columns are nominal, so use One-Hot Encoding with the get_dummies() function

temp_df = pd.get_dummies(games[['Team','Genres']])

# merge one-hot encoded columns back with original DataFrame

games = games.join(temp_df)

# drop the original Team and Genres columns as they're no longer required

games.drop('Team', axis=1, inplace=True)
games.drop('Genres', axis=1, inplace=True)

In [157]:
games

,Title,Rating,Number of Reviews,Plays,Playing,Active Users,Team_07th Expansion,Team_2K Games,Team_2K Marin,Team_343 Industries,...,Genres_Point-and-Click,Genres_Puzzle,Genres_RPG,Genres_Racing,Genres_Real Time Strategy,Genres_Shooter,Genres_Simulator,Genres_Sport,Genres_Strategy,Genres_Visual Novel
0,Elden Ring,4.5,3900,17000,3800,0.22,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Hades,4.3,2900,21000,3200,0.15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,The Legend of Zelda: Breath of the Wild,4.4,4300,30000,2500,0.08,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Undertale,4.2,3500,28000,679,0.02,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Hollow Knight,4.4,3000,21000,2400,0.11,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,Back to the Future: The Game,3.2,94,763,5,0.01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1508,Team Sonic Racing,2.9,264,1500,49,0.03,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1509,Dragon's Dogma,3.7,210,1100,45,0.04,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1510,Baldur's Gate 3,4.1,165,269,79,0.29,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1511,The LEGO Movie Videogame,2.8,184,1700,11,0.01,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Save OHE data to a csv file

In [159]:
# once the dataframe has been cleaned, write it to a csv file 

games = games.to_csv('C:/Users/Mark/Documents/repos/group-coursework-ha/data/games_clean_ohe.csv', index = False)